### ISSUE TITLE
Optionally allow builtin scalars to be generated with their wrapper types

### ISSUE THREAD

**Issue by drmaas** [NYTimes/openapi2proto#101]
This will be useful when certain request/response fields are allowed to be null. Since protocol buffers prohibits null values, using a wrapper type allows one to check of the value is set. This also allows the api to distinguish between default values and unset values.

See the following for details:

https://developers.google.com/protocol-buffers/docs/proto#optional

https://developers.google.com/protocol-buffers/docs/proto3#default

https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto

**Comment by drmaas** [comment]
I can take this one up.

**Comment by drmaas** [comment]
@jprobinson I looked at that, and I think that while it works in some use cases, it ends up being sort of a hack to retrofit an api spec with multiple types for each property. In our spec, we have hundreds of properties, with the ability to do partial POST and PUT methods. This would be unmanageable for us.

My reasoning for adding this feature in this manner is that the openapi specification has a built-in mechanism for defining what is optional (`required` fields). It should be possible for a developer to identify if an optional field has been set or not. I though the easiest and most intuitive way of doing this was by specifying it as `required` in the `required` list.

And, considering that this behavior may not always be desired, I added a flag to enable it, with the default being disabled.

**Comment by jprobinson** [comment]
In Protobuf, It's possible for a scalar field to be required and _not_ exist in the payload. That's actually how Protobuf/JSON serialization works. A scalar will generally get omitted from the payload if it is in its default vault. With that in mind, the idea that "required" means a field is "nullable" doesn't quite mix well.

I generally consider the "required" field to just be a piece of documentation for developers to implement outside of the schema and the "type" field is what we look at when we want to see what to expect in the response. In that case, I feel the notation `"type": ["null", "string"], ` is much more clear as to what clients can expect as, in some languages, strings are not a nullable thing. For example this is the difference between a scalar `string` and an actual _struct_ in Go.

I'm poking around but not finding any exact docs, but can you find somewhere that states a `required` field _can_ be considered `null` for scalar types? If that is, in fact, what the spec declares, we can add this and look to removed the other solution. Otherwise, I'm a bit unsure of adding 2 separate means of auto-boxing. I want to make sure this tool is flexible, but also want to avoid "square peg/round hole" syndrome.

**Comment by jprobinson** [comment]
Sure. If it fits your use case, I'd be fine with having a new (false by default) flag to just blanket autobox all scalars in the schema. 👍

**Comment by drmaas** [comment]
@jprobinson the PR is updated to reflect that.
