### ISSUE TITLE
preserve descriptions and summary fields

### ISSUE THREAD

**Issue by tmc** [NYTimes/openapi2proto#13]
https://github.com/tmc/grpc-uber/blob/master/uber.proto this generated file doesn't reflect the comments from https://github.com/tmc/grpc-uber/blob/master/uber.openapi.yaml

**Comment by jprobinson** [comment]
I've been using the philosophy that the Swagger docs are for humans, proto specs are for computers, so I hadn't put much thought into including the comments as protoc doesn't care about them or include them in the generated code.

Also, I'm not quite sure how we'd translate most of the comments in that example file since they do not relate to anything in the .proto file.

Do you have a use case?

**Comment by tmc** [comment]
@jprobinson I meant the field and endpoint summaries and descriptions.

**Comment by jprobinson** [comment]
Well, that's a horse of a different color! Sounds like a reasonable request and pretty simple to implement.  I'll try and find some time this week to make it happen.

**Comment by tmc** [comment]
FWIW this is how grpc-gateway renders openapi from the proto file: https://github.com/gengo/grpc-gateway/blob/master/protoc-gen-swagger/genswagger/template.go#L479

```proto
// (summary here
//
// (description here)
message Foo {}
```
or
```proto
// (description here).
message Foo {}
```
